export const users = [
  {
    id: 1,
    name: "Ethan Gray",
    avatar: "man_1.png",
    follows: [2, 3, 4],
  },
  {
    id: 2,
    name: "Sophia Bennett",
    avatar: 'woman_1.png',
    follows: [1, 5],
  },
  {
    id: 3,
    name: "Logan Rivera",
    avatar: 'man.png',
    follows: [1, 4],
  },
  {
    id: 4,
    name: "Mason Reed",
    avatar: 'man_1.png',
    follows: [2, 3],
  },
  {
    id: 5,
    name: "Amelia Foster",
    avatar: 'woman.png',
    follows: [3, 4],
  },
]

export const data = [
  {
    id: 1,
    authorId: 1,
    PubDate: "2023-09-15",
    Rating: 4.5,
    Commentary: "Great service, very helpful staff.",
    Topic: "Adventure",
  },
  {
    id: 2,
    authorId: 2,
    PubDate: "2023-08-22",
    Rating: 3.0,
    Commentary: "Decent product, but shipping took too long.",
    Topic: "Adventure",
  },
  {
    id: 3,
    authorId: 3,
    PubDate: "2023-09-10",
    Rating: 5.0,
    Commentary: "Absolutely loved the experience, would recommend.",
    Topic: "Adventure",
  },
  {
    id: 4,
    authorId: 4,
    PubDate: "2023-09-01",
    Rating: 2.0,
    Commentary: "Poor quality, not as expected.",
    Topic: "Adventure",
  },
  {
    id: 5,
    authorId: 5,
    PubDate: "2023-08-29",
    Rating: 5.0,
    Commentary: "Great value for money, very satisfied.",
    Topic: "Nature",
  },
  {
    id: 6,
    authorId: 1,
    PubDate: "2023-08-14",
    Rating: 3.0,
    Commentary: "It was okay, nothing special.",
    Topic: "Nature",
  },
  {
    id: 7,
    authorId: 2,
    PubDate: "2023-09-18",
    Rating: 5.0,
    Commentary: "Amazing! Will definitely come back.",
    Topic: "Nature",
  },
  {
    id: 8,
    authorId: 3,
    PubDate: "2023-09-02",
    Rating: 4.0,
    Commentary: "Good overall, but room for improvement.",
    Topic: "Nature",
  },
  {
    id: 9,
    authorId: 4,
    PubDate: "2023-09-11",
    Rating: 4.0,
    Commentary: "Nice experience, friendly staff.",
    Topic: "Fashion",
  },
  {
    id: 10,
    authorId: 5,
    PubDate: "2023-08-30",
    Rating: 2.0,
    Commentary: "Not satisfied with the quality.",
    Topic: "Fashion",
  },
  {
    id: 11,
    authorId: 1,
    PubDate: "2023-09-03",
    Rating: 5.0,
    Commentary: "Fantastic service, will recommend to friends.",
    Topic: "Fashion",
  },
  {
    id: 12,
    authorId: 2,
    PubDate: "2023-09-12",
    Rating: 3.0,
    Commentary: "Average, nothing special.",
    Topic: "Fashion",
  },
  {
    id: 13,
    authorId: 3,
    PubDate: "2023-09-05",
    Rating: 5.0,
    Commentary: "Very happy with the product and service.",
    Topic: "Modern",
  },
  {
    id: 14,
    authorId: 4,
    PubDate: "2023-09-16",
    Rating: 4.0,
    Commentary: "Good, but can improve in certain areas.",
    Topic: "Modern",
  },
  {
    id: 15,
    authorId: 5,
    PubDate: "2023-08-27",
    Rating: 4.0,
    Commentary: "Service was nice but the product lacked quality.",
    Topic: "Modern",
  },
  {
    id: 16,
    authorId: 1,
    PubDate: "2023-09-08",
    Rating: 5.0,
    Commentary: "Excellent experience, very professional.",
    Topic: "Modern",
  },
  {
    id: 17,
    authorId: 2,
    PubDate: "2023-09-13",
    Rating: 4.0,
    Commentary: "Good service, but could be more responsive.",
    Topic: "Modern",
  },
  {
    id: 18,
    authorId: 3,
    PubDate: "2023-09-07",
    Rating: 2.0,
    Commentary: "Not very impressed with the overall experience.",
    Topic: "Modern",
  },
  {
    id: 19,
    authorId: 4,
    PubDate: "2023-09-19",
    Rating: 4.0,
    Commentary: "Overall good, a few areas need work.",
    Topic: "Modern",
  },
  {
    id: 20,
    authorId: 5,
    PubDate: "2023-09-20",
    Rating: 5.0,
    Commentary: "Really great product and excellent service.",
    Topic: "Modern",
  }
];
