export const data = [
    {
      id: 1,
      PersonName: "Ethan Gray",
      Avatar: "profile1.svg",
      PubDate: "2023-09-15",
      Rating: 4,
      Commentary: "Great service, very helpful staff.",
      Topic: "Adventure",
    },
    {
      id: 2,
      PersonName: "Sophia Bennett",
      Avatar: "profile2.svg",
      PubDate: "2023-08-22",
      Rating: 3,
      Commentary: "Decent product, but shipping took too long.",
      Topic: "Adventure",
    },
    {
      id: 3,
      PersonName: "Logan Rivera",
      Avatar: "profile3.svg",
      PubDate: "2023-09-10",
      Rating: 5,
      Commentary: "Absolutely loved the experience, would recommend.",
      Topic: "Adventure",
    },
    {
      id: 4,
      PersonName: "Mason Reed",
      Avatar: "profile4.svg",
      PubDate: "2023-09-01",
      Rating: 2,
      Commentary: "Poor quality, not as expected.",
      Topic: "Adventure",
    },
    {
      id: 5,
      PersonName: "Amelia Foster",
      Avatar: "profile1.svg",
      PubDate: "2023-08-29",
      Rating: 5,
      Commentary: "Great value for money, very satisfied.",
      Topic: "Nature",
    },
    {
      id: 6,
      PersonName: "Oliver Coleman",
      Avatar: "profile2.svg",
      PubDate: "2023-08-14",
      Rating: 3,
      Commentary: "It was okay, nothing special.",
      Topic: "Nature",
    },
    {
      id: 7,
      PersonName: "Lily Turner",
      Avatar: "profile3.svg",
      PubDate: "2023-09-18",
      Rating: 5,
      Commentary: "Amazing! Will definitely come back.",
      Topic: "Nature",
    },
    {
      id: 8,
      PersonName: "William Ross",
      Avatar: "profile4.svg",
      PubDate: "2023-09-02",
      Rating: 4,
      Commentary: "Good overall, but room for improvement.",
      Topic: "Nature",
    },
    {
      id: 9,
      PersonName: "Ava Cooper",
      Avatar: "profile1.svg",
      PubDate: "2023-09-11",
      Rating: 4,
      Commentary: "Nice experience, friendly staff.",
      Topic: "Fashion",
    },
    {
      id: 10,
      PersonName: "James Morgan",
      Avatar: "profile2.svg",
      PubDate: "2023-08-30",
      Rating: 2,
      Commentary: "Not satisfied with the quality.",
      Topic: "Fashion",
    },
    {
      id: 11,
      PersonName: "Charlotte Brooks",
      Avatar: "profile3.svg",
      PubDate: "2023-09-03",
      Rating: 5,
      Commentary: "Fantastic service, will recommend to friends.",
      Topic: "Fashion",
    },
    {
      id: 12,
      PersonName: "Jackson Ward",
      Avatar: "profile4.svg",
      PubDate: "2023-09-12",
      Rating: 3,
      Commentary: "Average, nothing special.",
      Topic: "Fashion",
    },
    {
      id: 13,
      PersonName: "Harper Jenkins",
      Avatar: "profile1.svg",
      PubDate: "2023-09-05",
      Rating: 5,
      Commentary: "Very happy with the product and service.",
      Topic: "Modern",
    },
    {
      id: 14,
      PersonName: "Daniel Phillips",
      Avatar: "profile2.svg",
      PubDate: "2023-09-16",
      Rating: 4,
      Commentary: "Good, but can improve in certain areas.",
      Topic: "Modern",
    },
    {
      id: 15,
      PersonName: "Ella Simmons",
      Avatar: "profile3.svg",
      PubDate: "2023-08-27",
      Rating: 4,
      Commentary: "Service was nice but the product lacked quality.",
      Topic: "Modern",
    },
    {
      id: 16,
      PersonName: "Michael Sanders",
      Avatar: "profile4.svg",
      PubDate: "2023-09-08",
      Rating: 5,
      Commentary: "Excellent experience, very professional.",
      Topic: "Modern",
    },
    {
      id: 17,
      PersonName: "Abigail Bailey",
      Avatar: "profile1.svg",
      PubDate: "2023-09-13",
      Rating: 4,
      Commentary: "Good service, but could be more responsive.",
      Topic: "Modern",
    },
    {
      id: 18,
      PersonName: "Samuel Howard",
      Avatar: "profile2.svg",
      PubDate: "2023-09-07",
      Rating: 2,
      Commentary: "Not very impressed with the overall experience.",
      Topic: "Modern",
    },
    {
      id: 19,
      PersonName: "Leah Foster",
      Avatar: "profile3.svg",
      PubDate: "2023-09-19",
      Rating: 4,
      Commentary: "Overall good, a few areas need work.",
      Topic: "Modern",
    },
    {
      id: 20,
      PersonName: "Benjamin Bell",
      Avatar: "profile4.svg",
      PubDate: "2023-09-20",
      Rating: 5,
      Commentary: "Really great product and excellent service.",
      Topic: "Modern",
    },
  ];
  